In [ ]:
import pandas as pd

dataset = pd.read_csv('D:\\NewFinalDatasetsForNeuralNetwork\\New_Encap_25_50_75_NoCrash_01_99_crash_noncrash_combined_csv_24_03_2023__11_02.csv')

In [1]:
import pandas as pd
dataset = pd.read_csv('D:\\NewFinalDatasetsForNeuralNetwork\\New_Encap_25_50_75_NoCrash_01_99_crash_noncrash_combined_csv_24_03_2023__11_02.csv')

In [2]:
dataset = dataset.dropna()
dataset

NORMALIZED PEDESTRIAN POSITION X  NORMALIZED PEDESTRIAN POSITION Y  \
0                               17.641040                              -4.0   
2                              107.172928                              -7.9   
3                               63.520570                              -5.0   
4                               70.149323                              -6.2   
5                               97.835186                              -6.0   
...                                   ...                               ...   
2029239                         44.990099                              -3.9   
2029240                         85.613583                              -6.3   
2029241                        -25.429082                              -1.1   
2029242                         58.835404                              -5.7   
2029243                         23.449532                              -2.1   

         NORMALIZED PEDESTRIAN DIRECTION  NORMALIZED PEDESTRIAN SPEED  \
0                                   6.90                     0.916667   
2                                   3.82                     1.111111   
3                                   1.05                     1.250000   
4                                   3.06                     1.166667   
5                                   4.40                     1.305556   
...                                  ...                          ...   
2029239                             0.17                     1.111111   
2029240                             9.60                     0.555556   
2029241                             7.40                     0.944444   
2029242                             2.79                     1.277778   
2029243                             1.60                     1.388889   

              TTC  
0             inf  
2        7.576834  
3        4.400739  
4        4.892690  
5             inf  
...           ...  
2029239  3.060013  
2029240       inf  
2029241       inf  
2029242  4.074395  
2029243  1.512590  

[2012720 rows x 5 columns]

In [3]:
import numpy as np
dataset['TTC'] = np.where(dataset['TTC'] < 0, 0, dataset['TTC']).tolist()
dataset

NORMALIZED PEDESTRIAN POSITION X  NORMALIZED PEDESTRIAN POSITION Y  \
0                               17.641040                              -4.0   
2                              107.172928                              -7.9   
3                               63.520570                              -5.0   
4                               70.149323                              -6.2   
5                               97.835186                              -6.0   
...                                   ...                               ...   
2029239                         44.990099                              -3.9   
2029240                         85.613583                              -6.3   
2029241                        -25.429082                              -1.1   
2029242                         58.835404                              -5.7   
2029243                         23.449532                              -2.1   

         NORMALIZED PEDESTRIAN DIRECTION  NORMALIZED PEDESTRIAN SPEED  \
0                                   6.90                     0.916667   
2                                   3.82                     1.111111   
3                                   1.05                     1.250000   
4                                   3.06                     1.166667   
5                                   4.40                     1.305556   
...                                  ...                          ...   
2029239                             0.17                     1.111111   
2029240                             9.60                     0.555556   
2029241                             7.40                     0.944444   
2029242                             2.79                     1.277778   
2029243                             1.60                     1.388889   

              TTC  
0             inf  
2        7.576834  
3        4.400739  
4        4.892690  
5             inf  
...           ...  
2029239  3.060013  
2029240       inf  
2029241       inf  
2029242  4.074395  
2029243  1.512590  

[2012720 rows x 5 columns]

In [4]:
import numpy as np

# Create a new column 'Scenario type' and map values to 'crash' or 'no_crash' based on their TTC range
bins = [-1, 7, np.inf]
labels = ['crash', 'no_crash']
dataset['SCENARIO TYPE'] = pd.cut(dataset['TTC'], bins=bins, labels=labels)

In [5]:
min(dataset['TTC'])

0.0

In [6]:
dataset

NORMALIZED PEDESTRIAN POSITION X  NORMALIZED PEDESTRIAN POSITION Y  \
0                               17.641040                              -4.0   
2                              107.172928                              -7.9   
3                               63.520570                              -5.0   
4                               70.149323                              -6.2   
5                               97.835186                              -6.0   
...                                   ...                               ...   
2029239                         44.990099                              -3.9   
2029240                         85.613583                              -6.3   
2029241                        -25.429082                              -1.1   
2029242                         58.835404                              -5.7   
2029243                         23.449532                              -2.1   

         NORMALIZED PEDESTRIAN DIRECTION  NORMALIZED PEDESTRIAN SPEED  \
0                                   6.90                     0.916667   
2                                   3.82                     1.111111   
3                                   1.05                     1.250000   
4                                   3.06                     1.166667   
5                                   4.40                     1.305556   
...                                  ...                          ...   
2029239                             0.17                     1.111111   
2029240                             9.60                     0.555556   
2029241                             7.40                     0.944444   
2029242                             2.79                     1.277778   
2029243                             1.60                     1.388889   

              TTC SCENARIO TYPE  
0             inf      no_crash  
2        7.576834      no_crash  
3        4.400739         crash  
4        4.892690         crash  
5             inf      no_crash  
...           ...           ...  
2029239  3.060013         crash  
2029240       inf      no_crash  
2029241       inf      no_crash  
2029242  4.074395         crash  
2029243  1.512590         crash  

[2012720 rows x 6 columns]

In [7]:
from sklearn.preprocessing import OneHotEncoder

# Select column to one-hot encode
col_to_encode = 'SCENARIO TYPE'

# Perform one-hot-encoding
one_hot_encoded = pd.get_dummies(dataset[col_to_encode], prefix=col_to_encode)

# Append one-hot encoded columns to original dataset
dataset = pd.concat([dataset, one_hot_encoded], axis=1)

# Drop original column that was one-hot encoded
dataset = dataset.drop(col_to_encode, axis=1)
dataset

NORMALIZED PEDESTRIAN POSITION X  NORMALIZED PEDESTRIAN POSITION Y  \
0                               17.641040                              -4.0   
2                              107.172928                              -7.9   
3                               63.520570                              -5.0   
4                               70.149323                              -6.2   
5                               97.835186                              -6.0   
...                                   ...                               ...   
2029239                         44.990099                              -3.9   
2029240                         85.613583                              -6.3   
2029241                        -25.429082                              -1.1   
2029242                         58.835404                              -5.7   
2029243                         23.449532                              -2.1   

         NORMALIZED PEDESTRIAN DIRECTION  NORMALIZED PEDESTRIAN SPEED  \
0                                   6.90                     0.916667   
2                                   3.82                     1.111111   
3                                   1.05                     1.250000   
4                                   3.06                     1.166667   
5                                   4.40                     1.305556   
...                                  ...                          ...   
2029239                             0.17                     1.111111   
2029240                             9.60                     0.555556   
2029241                             7.40                     0.944444   
2029242                             2.79                     1.277778   
2029243                             1.60                     1.388889   

              TTC  SCENARIO TYPE_crash  SCENARIO TYPE_no_crash  
0             inf                    0                       1  
2        7.576834                    0                       1  
3        4.400739                    1                       0  
4        4.892690                    1                       0  
5             inf                    0                       1  
...           ...                  ...                     ...  
2029239  3.060013                    1                       0  
2029240       inf                    0                       1  
2029241       inf                    0                       1  
2029242  4.074395                    1                       0  
2029243  1.512590                    1                       0  

[2012720 rows x 7 columns]

In [8]:
# drop original TTC column from the dataset as it is now one-hot encoded
dataset = dataset.drop('TTC', axis=1)
dataset

NORMALIZED PEDESTRIAN POSITION X  NORMALIZED PEDESTRIAN POSITION Y  \
0                               17.641040                              -4.0   
2                              107.172928                              -7.9   
3                               63.520570                              -5.0   
4                               70.149323                              -6.2   
5                               97.835186                              -6.0   
...                                   ...                               ...   
2029239                         44.990099                              -3.9   
2029240                         85.613583                              -6.3   
2029241                        -25.429082                              -1.1   
2029242                         58.835404                              -5.7   
2029243                         23.449532                              -2.1   

         NORMALIZED PEDESTRIAN DIRECTION  NORMALIZED PEDESTRIAN SPEED  \
0                                   6.90                     0.916667   
2                                   3.82                     1.111111   
3                                   1.05                     1.250000   
4                                   3.06                     1.166667   
5                                   4.40                     1.305556   
...                                  ...                          ...   
2029239                             0.17                     1.111111   
2029240                             9.60                     0.555556   
2029241                             7.40                     0.944444   
2029242                             2.79                     1.277778   
2029243                             1.60                     1.388889   

         SCENARIO TYPE_crash  SCENARIO TYPE_no_crash  
0                          0                       1  
2                          0                       1  
3                          1                       0  
4                          1                       0  
5                          0                       1  
...                      ...                     ...  
2029239                    1                       0  
2029240                    0                       1  
2029241                    0                       1  
2029242                    1                       0  
2029243                    1                       0  

[2012720 rows x 6 columns]

In [9]:
from sklearn.model_selection import train_test_split

# Split dataset into features and labels
X = dataset.drop(columns=["SCENARIO TYPE_crash", "SCENARIO TYPE_no_crash"]).values
y = dataset[["SCENARIO TYPE_crash", "SCENARIO TYPE_no_crash"]].values

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
import numpy as np

# Assuming y_train and y_test are the one-hot encoded target variables for train and test sets respectively
train_class_counts = np.sum(y_train, axis=0)
test_class_counts = np.sum(y_test, axis=0)

# Calculate class proportions
train_class_props = train_class_counts / np.sum(train_class_counts)
test_class_props = test_class_counts / np.sum(test_class_counts)

print("Train class proportions:", train_class_props)
print("Test class proportions:", test_class_props)

Train class proportions: [0.58366539 0.41633461]
Test class proportions: [0.58302198 0.41697802]


In [11]:
import tensorflow as tf
import keras
from keras import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

# Defining first layer of the neural network, which normalizes the input data on the fly
normalizer_layer = keras.layers.Normalization(axis=-1)
normalizer_layer = keras.layers.Normalization(input_shape=[4,], axis=None)

# Adapting normalizer layer to the input train data shape
normalizer_layer.adapt(np.array(X_train))

# Defining the model and compilation
def build_and_compile_model(normalizer_layer):
  nn_model = keras.Sequential([
      normalizer_layer,
      keras.layers.Dense(128, activation='relu', kernel_initializer='he_uniform'),
      keras.layers.Dense(64, activation='sigmoid'),
      keras.layers.Dense(32, activation='relu'),
      #keras.layers.Dense(32, activation='sigmoid'),
      #keras.layers.Dense(128, activation='sigmoid'),
      keras.layers.Dense(y.shape[1], activation="softmax")
  ])

  nn_model.compile(loss='binary_crossentropy', optimizer=tf.keras.optimizers.Adam(0.01), metrics=["categorical_accuracy"])
  return nn_model

In [13]:
classification_model = build_and_compile_model(normalizer_layer)

# Training the model
history = classification_model.fit(X_train, y_train, epochs=10, batch_size=128, validation_data=(X_test, y_test))

# Evaluating the model using the test set
loss, accuracy = classification_model.evaluate(X_test, y_test)
print("Test set accuracy:", accuracy)

Epoch 1/10
12580/12580 [==============================] - 58s 5ms/step - loss: 0.0852 - categorical_accuracy: 0.9730 - val_loss: 0.0237 - val_categorical_accuracy: 0.9936
Epoch 2/10
12580/12580 [==============================] - 54s 4ms/step - loss: 0.0592 - categorical_accuracy: 0.9813 - val_loss: 0.0372 - val_categorical_accuracy: 0.9860
Epoch 3/10
12580/12580 [==============================] - 47s 4ms/step - loss: 0.0535 - categorical_accuracy: 0.9849 - val_loss: 0.0187 - val_categorical_accuracy: 0.9944
Epoch 4/10
12580/12580 [==============================] - 47s 4ms/step - loss: 0.0529 - categorical_accuracy: 0.9851 - val_loss: 0.0467 - val_categorical_accuracy: 0.9906
Epoch 5/10
12580/12580 [==============================] - 52s 4ms/step - loss: 0.0895 - categorical_accuracy: 0.9748 - val_loss: 0.0687 - val_categorical_accuracy: 0.9842
Epoch 6/10
12580/12580 [==============================] - 58s 5ms/step - loss: 0.0781 - categorical_accuracy: 0.9780 - val_loss: 0.1074 - val_cat

In [ ]:
#! pip install graphviz pydot
import tensorflow as tf
import keras
import numpy as np
from keras.utils import plot_model

# Plot model structure image Assume 'model' is a trained neural network model
plot_model(classification_model, to_file='C:\\Users\\thiru\\OneDrive\\Desktop\\Aashritha project\\NeuralNetModel Structures\\regression_model_diagram_Alternative.png', show_shapes=True, show_layer_names=True)

In [ ]:
from ann_visualizer.visualize import ann_viz
# Visualize the model architecture with ann_viz
ann_viz(classification_model, view=True, filename='C:\\Users\\thiru\\OneDrive\\Desktop\\Aashritha project\\NeuralNetModel Structures\\regression_model_Architecture_diagram', title='Regression Model Architecture')

In [ ]:
classification_model = build_and_compile_model(normalizer_layer)

# Training the model
history = classification_model.fit(X_train, y_train, epochs=15, batch_size=128, validation_data=(X_test, y_test))

# Evaluating the model using the test set
loss, accuracy = classification_model.evaluate(X_test, y_test)
print("Test set accuracy:", accuracy)

In [ ]:
classification_model.save('NewDataset_04_04_TTC_classification_model.h5')

In [15]:
# print x-test
print(f'{X_test[:10]}  {y_test[:10]}\n')
# Output as a single class, input 01 corresponds to output 1 (No Crash) and 10 Corresponds to output 0 (Crash) 
#print(f'{y_test[:10]}\n')
prediction = classification_model.predict(X_test[:10])
#print(f'{prediction}\n')
print((prediction.argmax(axis=1)).reshape((-1, 1)))

[[235.72034956  -5.4          3.1          0.5       ]
 [ 39.06521306  -3.6          4.48         1.36111111]
 [  9.29469631  -0.6          3.36         1.22222222]
 [ 39.58782481  -0.5          7.2          1.30555556]
 [110.73661569  -2.4          7.6          0.69444444]
 [ 59.10887816  -0.4          5.7          0.83333333]
 [-60.66430739  -0.6          4.5          0.52777778]
 [ 24.87898493  -4.3          2.4          0.80555556]
 [ 58.05313021  -4.9          1.84         1.22222222]
 [ 80.85006665  -6.6          2.65         1.16666667]]  [[0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]]

1/1 [==============================] - 0s 103ms/step
[[1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
