In [55]:
import pandas as pd

dataset = pd.read_csv('D:\\NewFinalDatasetsForNeuralNetwork\\New_Encap_25_50_75_NoCrash_01_99_crash_noncrash_combined_csv_24_03_2023__11_02.csv')
dataset

NORMALIZED PEDESTRIAN POSITION X  NORMALIZED PEDESTRIAN POSITION Y  \
0                               17.641040                              -4.0   
1                                     NaN                              -0.5   
2                              107.172928                              -7.9   
3                               63.520570                              -5.0   
4                               70.149323                              -6.2   
...                                   ...                               ...   
2029239                         44.990099                              -3.9   
2029240                         85.613583                              -6.3   
2029241                        -25.429082                              -1.1   
2029242                         58.835404                              -5.7   
2029243                         23.449532                              -2.1   

         NORMALIZED PEDESTRIAN DIRECTION  NORMALIZED PEDESTRIAN SPEED  \
0                                   6.90                     0.916667   
1                                   4.40                     0.000000   
2                                   3.82                     1.111111   
3                                   1.05                     1.250000   
4                                   3.06                     1.166667   
...                                  ...                          ...   
2029239                             0.17                     1.111111   
2029240                             9.60                     0.555556   
2029241                             7.40                     0.944444   
2029242                             2.79                     1.277778   
2029243                             1.60                     1.388889   

              TTC  
0             inf  
1             inf  
2        7.576834  
3        4.400739  
4        4.892690  
...           ...  
2029239  3.060013  
2029240       inf  
2029241       inf  
2029242  4.074395  
2029243  1.512590  

[2029244 rows x 5 columns]

In [56]:
dataset = dataset.dropna()
dataset = dataset.drop_duplicates()
dataset = dataset.drop(dataset[dataset['TTC'] < 0].index)
dataset

NORMALIZED PEDESTRIAN POSITION X  NORMALIZED PEDESTRIAN POSITION Y  \
0                               17.641040                              -4.0   
2                              107.172928                              -7.9   
3                               63.520570                              -5.0   
4                               70.149323                              -6.2   
5                               97.835186                              -6.0   
...                                   ...                               ...   
2029239                         44.990099                              -3.9   
2029240                         85.613583                              -6.3   
2029241                        -25.429082                              -1.1   
2029242                         58.835404                              -5.7   
2029243                         23.449532                              -2.1   

         NORMALIZED PEDESTRIAN DIRECTION  NORMALIZED PEDESTRIAN SPEED  \
0                                   6.90                     0.916667   
2                                   3.82                     1.111111   
3                                   1.05                     1.250000   
4                                   3.06                     1.166667   
5                                   4.40                     1.305556   
...                                  ...                          ...   
2029239                             0.17                     1.111111   
2029240                             9.60                     0.555556   
2029241                             7.40                     0.944444   
2029242                             2.79                     1.277778   
2029243                             1.60                     1.388889   

              TTC  
0             inf  
2        7.576834  
3        4.400739  
4        4.892690  
5             inf  
...           ...  
2029239  3.060013  
2029240       inf  
2029241       inf  
2029242  4.074395  
2029243  1.512590  

[2004687 rows x 5 columns]

In [57]:
import numpy as np

# Create a new column 'Scenario type' and map values to 'crash' or 'no_crash' based on their TTC range
bins = [-1, 7, np.inf]
labels = ['crash', 'no_crash']
dataset['SCENARIO TYPE'] = pd.cut(dataset['TTC'], bins=bins, labels=labels)
dataset

NORMALIZED PEDESTRIAN POSITION X  NORMALIZED PEDESTRIAN POSITION Y  \
0                               17.641040                              -4.0   
2                              107.172928                              -7.9   
3                               63.520570                              -5.0   
4                               70.149323                              -6.2   
5                               97.835186                              -6.0   
...                                   ...                               ...   
2029239                         44.990099                              -3.9   
2029240                         85.613583                              -6.3   
2029241                        -25.429082                              -1.1   
2029242                         58.835404                              -5.7   
2029243                         23.449532                              -2.1   

         NORMALIZED PEDESTRIAN DIRECTION  NORMALIZED PEDESTRIAN SPEED  \
0                                   6.90                     0.916667   
2                                   3.82                     1.111111   
3                                   1.05                     1.250000   
4                                   3.06                     1.166667   
5                                   4.40                     1.305556   
...                                  ...                          ...   
2029239                             0.17                     1.111111   
2029240                             9.60                     0.555556   
2029241                             7.40                     0.944444   
2029242                             2.79                     1.277778   
2029243                             1.60                     1.388889   

              TTC SCENARIO TYPE  
0             inf      no_crash  
2        7.576834      no_crash  
3        4.400739         crash  
4        4.892690         crash  
5             inf      no_crash  
...           ...           ...  
2029239  3.060013         crash  
2029240       inf      no_crash  
2029241       inf      no_crash  
2029242  4.074395         crash  
2029243  1.512590         crash  

[2004687 rows x 6 columns]

In [58]:
from sklearn.preprocessing import OneHotEncoder

# Select column to one-hot encode
col_to_encode = 'SCENARIO TYPE'

# Perform one-hot-encoding
one_hot_encoded = pd.get_dummies(dataset[col_to_encode], prefix=col_to_encode)

# Append one-hot encoded columns to original dataset
dataset = pd.concat([dataset, one_hot_encoded], axis=1)

# Drop original column that was one-hot encoded
dataset = dataset.drop(col_to_encode, axis=1)
dataset

NORMALIZED PEDESTRIAN POSITION X  NORMALIZED PEDESTRIAN POSITION Y  \
0                               17.641040                              -4.0   
2                              107.172928                              -7.9   
3                               63.520570                              -5.0   
4                               70.149323                              -6.2   
5                               97.835186                              -6.0   
...                                   ...                               ...   
2029239                         44.990099                              -3.9   
2029240                         85.613583                              -6.3   
2029241                        -25.429082                              -1.1   
2029242                         58.835404                              -5.7   
2029243                         23.449532                              -2.1   

         NORMALIZED PEDESTRIAN DIRECTION  NORMALIZED PEDESTRIAN SPEED  \
0                                   6.90                     0.916667   
2                                   3.82                     1.111111   
3                                   1.05                     1.250000   
4                                   3.06                     1.166667   
5                                   4.40                     1.305556   
...                                  ...                          ...   
2029239                             0.17                     1.111111   
2029240                             9.60                     0.555556   
2029241                             7.40                     0.944444   
2029242                             2.79                     1.277778   
2029243                             1.60                     1.388889   

              TTC  SCENARIO TYPE_crash  SCENARIO TYPE_no_crash  
0             inf                    0                       1  
2        7.576834                    0                       1  
3        4.400739                    1                       0  
4        4.892690                    1                       0  
5             inf                    0                       1  
...           ...                  ...                     ...  
2029239  3.060013                    1                       0  
2029240       inf                    0                       1  
2029241       inf                    0                       1  
2029242  4.074395                    1                       0  
2029243  1.512590                    1                       0  

[2004687 rows x 7 columns]

In [59]:
# Split dataset into features and labels
X = dataset.drop(columns=["TTC", "SCENARIO TYPE_crash", "SCENARIO TYPE_no_crash"]).values
y_regression = dataset[["TTC"]].values
y_classification = dataset[["SCENARIO TYPE_crash", "SCENARIO TYPE_no_crash"]].values
n_features = X.shape[1]
print(X)
print(n_features)
print(y_classification)
print(y_regression)

[[ 17.64103969  -4.           6.9          0.91666667]
 [107.1729282   -7.9          3.82         1.11111111]
 [ 63.5205703   -5.           1.05         1.25      ]
 ...
 [-25.42908162  -1.1          7.4          0.94444444]
 [ 58.8354041   -5.7          2.79         1.27777778]
 [ 23.44953247  -2.1          1.6          1.38888889]]
4
[[0 1]
 [0 1]
 [1 0]
 ...
 [0 1]
 [1 0]
 [1 0]]
[[       inf]
 [7.57683365]
 [4.40073895]
 ...
 [       inf]
 [4.07439481]
 [1.51258974]]


In [54]:
from numpy import unique

n_class = len(unique(y_classification))
n_class

2

In [60]:
from sklearn.model_selection import train_test_split
# Split dataset into training and testing sets
X_train, X_test, y_train_classification, y_test_classification, y_train_regression, y_test_regression  = train_test_split(X, y_classification, y_regression, test_size=0.2, random_state=42)

In [61]:
print(f' ytrain classification ------>\n {y_train_classification}')
print(f' ytrain regression ------>\n {y_train_regression}')
print(f' xtrain ------>\n {X_train}')

 ytrain classification ------>
 [[1 0]
 [1 0]
 [0 1]
 ...
 [1 0]
 [1 0]
 [1 0]]
 ytrain regression ------>
 [[5.76372491]
 [2.78468511]
 [       inf]
 ...
 [4.68634113]
 [4.01207509]
 [0.80926495]]
 xtrain ------>
 [[ 82.29275601  -6.7          2.06         1.25      ]
 [ 40.86678507  -3.7          4.78         1.33333333]
 [-22.55439816  -2.6          4.8          0.22222222]
 ...
 [ 67.11548876  -5.6          4.43         1.30555556]
 [ 58.03416958  -5.4          2.21         1.22222222]
 [ 13.682335    -1.1          2.99         1.36111111]]


In [77]:
# import tensorflow as tf
# from tensorflow import keras
# from keras import layers

# class MyModel(keras.Model):
#     def __init__(self, input_shape):
#         super(MyModel, self).__init__()
#         self.normalization = layers.Normalization(input_shape=[4,], axis=None)
#         self.dense1 = layers.Dense(128, activation='relu')
#         self.dense2 = layers.Dense(64, activation='sigmoid')
#         self.dense3 = layers.Dense(32, activation='relu')
#         self.classification_output = layers.Dense(2, activation='softmax')
#         #keras.layers.Dense(1,name = 'Output_Layer')
        
#         self.dense4 = layers.Dense(64, activation='relu')
#         #model.add(BatchNormalization())
#         self.dense5 = layers.Dense(128, activation='relu')
#         self.dense6 = layers.Dense(64, activation='relu')
#         self.regression_output = layers.Dense(1, activation='linear')
    
#     # def call(self, inputs):
#     #     # Normalize the inputs
#     #     normalized_inputs = self.normalization(inputs)
        
#     #     # Pass the inputs through the classification layers
#     #     x = self.dense1(normalized_inputs)
#     #     x = self.dense2(x)
#     #     x = self.dense3(x)
#     #     classification_output = self.classification_output(x)
        
#     #     # Check if the classification output is 0
#     #     if tf.equal(tf.argmax(classification_output, axis=1), 0):
#     #         # Pass the original inputs through the regression layers
#     #         x = self.dense4(normalized_inputs)
#     #         x = self.dense5(x)
#     #         x = self.dense6(x)
#     #         regression_output = self.regression_output(x)
#     #         return regression_output
#     #     else:
#     #         return classification_output 
         
#     # def build(self, input_shape=(None, 4)):
#     #     self.normalization.build(input_shape)
#     #     self.dense1.build(input_shape)
#     #     self.dense2.build((None, 128))
#     #     self.dense3.build((None, 64))
#     #     self.classification_output.build((None, 32))
#     #     self.dense4.build(input_shape)
#     #     self.dense5.build((None, 64))
#     #     self.dense6.build((None, 128))
#     #     self.regression_output.build((None, 64))
#     #     super(MyModel, self).build(input_shape)   


#     def call(self, inputs):
#         # Normalize the inputs
#          normalized_inputs = self.normalization(inputs)

#          # Pass the inputs through the classification layers
#         x = self.dense1(normalized_inputs)
#         x = self.dense2(x)
#         x = self.dense3(x)
#         classification_output = self.classification_output(x)

#         # Check if the classification output is 0
#         is_zero = tf.equal(tf.argmax(classification_output, axis=1), 0)

#          # Define the computation for the two cases
#          def regression_case():
#         # Pass the original inputs through the regression layers
#             x = self.dense4(normalized_inputs)
#             x = self.dense5(x)
#             x = self.dense6(x)
#             return self.regression_output(x)

#         def classification_case():
#             return classification_output

#         # Conditionally execute the appropriate computation
#         output = tf.cond(is_zero, regression_case, classification_case)
#         return output

In [ ]:

# # mlp for combined regression and classification predictions on the abalone dataset
# from numpy import unique
# from numpy import argmax
# from pandas import read_csv
# from sklearn.metrics import mean_absolute_error
# from sklearn.metrics import accuracy_score
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import LabelEncoder
# from keras.models import Model
# from keras.layers import Input
# from keras.layers import Dense, Normalization
# from keras.utils import plot_model

# # input
# normalization_layer = Normalization()
# normalization_layer.adapt(X)
# visible = Input(shape=(n_features,))
# normalization = normalization_layer(visible)
# hidden1 = Dense(20, activation='relu', kernel_initializer='he_normal')(visible)
# hidden2 = Dense(10, activation='relu', kernel_initializer='he_normal')(hidden1)
# # regression output
# out_reg = Dense(1, activation='linear')(hidden2)
# # classification output
# out_clas = Dense(n_class, activation='softmax')(hidden2)
# # define model
# model = Model(inputs=visible, outputs=[out_reg, out_clas])
# # compile the keras model
# model.compile(loss=['mse','sparse_categorical_crossentropy'], optimizer='adam')
# # plot graph of model
# plot_model(model, to_file='model.png', show_shapes=True)
# # fit the keras model on the dataset
# model.fit(X_train, [y_train,y_train_class], epochs=150, batch_size=32, verbose=2)
# # make predictions on test set
# yhat1, yhat2 = model.predict(X_test)
# # calculate error for regression model
# error = mean_absolute_error(y_test, yhat1)
# print('MAE: %.3f' % error)
# # evaluate accuracy for classification model
# yhat2 = argmax(yhat2, axis=-1).astype('int')
# acc = accuracy_score(y_test_class, yhat2)
# print('Accuracy: %.3f' % acc)


In [68]:
import tensorflow as tf
from tensorflow import keras
from keras import layers
from keras.layers import Input
from keras.layers import Dense, Normalization

class MyModel(keras.Model):
    def __init__(self, n_features):
        super(MyModel, self).__init__()
        visible = Input(shape=(n_features,))
        self.normalization = layers.Normalization(input_shape= (n_features,), axis=None)
        #self.normalization.adapt(np.array(X_train))
        self.dense1 = layers.Dense(128, activation='relu')
        self.dense2 = layers.Dense(64, activation='sigmoid')
        self.dense3 = layers.Dense(32, activation='relu')
        self.classification_output = layers.Dense(n_class, activation='softmax')
        
        self.dense4 = layers.Dense(64, activation='relu')
        #model.add(BatchNormalization())
        self.dense5 = layers.Dense(128, activation='relu')
        self.dense6 = layers.Dense(64, activation='relu')
        self.regression_output = layers.Dense(1)
        
    def call(self, inputs):
        # Normalize the inputs
        normalized_inputs = self.normalization(inputs)

        # Pass the inputs through the classification layers
        y = self.dense1(normalized_inputs)
        y = self.dense2(y)
        y = self.dense3(y)
        classification_output = self.classification_output(y)

        # Check if the classification output is 0
        is_zero = tf.equal(tf.argmax(classification_output, axis=1), 0)

         # Define the computation for the two cases
        def regression_case():
        # Pass the original inputs through the regression layers
            x = self.dense4(normalized_inputs)
            x = self.dense5(x)
            x = self.dense6(x)
            return self.regression_output(x)

        def classification_case():
            return classification_output

        # Conditionally execute the appropriate computation
        output = tf.cond(is_zero, regression_case, classification_case)
        return output

In [120]:
# from tensorflow import keras
# from keras.layers import Dense, Normalization, Input
# from keras.models import Model

# def create_model(input_shape):
#     inputs = Input(shape=input_shape)
#     x = Normalization(axis=None)(inputs)
#     x = Dense(128, activation='relu')(x)
#     x = Dense(64, activation='sigmoid')(x)
#     x = Dense(32, activation='relu')(x)
#     classification_output = Dense(2, activation='softmax')(x)
#     y = Dense(64, activation='relu')(inputs)
#     y = Dense(128, activation='relu')(y)
#     y = Dense(64, activation='relu')(y)
#     regression_output = Dense(1, activation='linear')(y)
    
#     is_zero = keras.layers.Lambda(lambda x: tf.equal(tf.argmax(x, axis=1), 0))(classification_output)
    
#     output = keras.layers.Lambda(lambda x: tf.cond(x[0], lambda: x[1], lambda: x[2]))([is_zero, regression_output, classification_output])
    
#     model = Model(inputs=inputs, outputs=output)
#     return model

# model = create_model(input_shape=(4,))

In [71]:
from keras import Model
# Create input layer
inputs = Input(shape=(n_features,))
# Instantiate model
my_model = MyModel(n_features)
# Call model on input layer
outputs = my_model(inputs)
model = Model(inputs=inputs, outputs=outputs)

# Define different loss, optimizer, and learning rate for classification and regression
# classification_loss = 'binary_crossentropy'
# classification_optimizer = keras.optimizers.Adam(learning_rate=0.01)
classification_metrics = ['categorical_accuracy']

# regression_loss = 'mean_squared_error'
# regression_optimizer = keras.optimizers.Adam(learning_rate=0.01)
regression_metrics = ['mse']

# Create an instance of the model
#model = MyModel(input_shape=(None, 4))
#model = create_model(input_shape=[4,])
model.compile(loss=['binary_crossentropy', 'mse'], optimizer='adam',metrics=[classification_metrics, regression_metrics])
# Compile the model with different loss, optimizer, and learning rate for classification and regression
# model.compile(loss=[classification_loss, regression_loss],
#               optimizer = keras.optimizers.Adam(learning_rate=0.01),
#               metrics=[classification_metrics, regression_metrics])
# model.build(input_shape=(None, 4))
# #input_shape=(None, 4)

In [36]:
y_train_classification = y_train_classification.reshape(-1, )
y_train_regression = y_train_regression.reshape(-1, )


In [65]:
print(type(y_train_classification))
print(type(y_train_regression))
print(type((X_train)))
z = [y_train_classification, y_train_regression]
print(type((z)))
print(z)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'list'>
[array([[1, 0],
       [1, 0],
       [0, 1],
       ...,
       [1, 0],
       [1, 0],
       [1, 0]], dtype=uint8), array([[5.76372491],
       [2.78468511],
       [       inf],
       ...,
       [4.68634113],
       [4.01207509],
       [0.80926495]])]


In [72]:

# mask = np.logical_and(np.isfinite(y_train_regression).flatten(), ~np.isnan(y_train_classification).any(axis=1))
# X_train = X_train[mask]
# y_train_classification = y_train_classification[mask]
# y_train_regression = y_train_regression[mask]

# Train the model
history = model.fit(X_train, [y_train_classification, y_train_regression], epochs=10, batch_size = 32)


Epoch 1/10


InvalidArgumentError: Graph execution error:

The second input must be a scalar, but it has shape [32]
	 [[{{node gradient_tape/model_2/my_model_4/cond/StatelessIf/model_2/my_model_4/normalization_4/truediv/_37}}]] [Op:__inference_train_function_8218]

In [42]:
model.fit?

Signature:
model.fit(
    x=None,
    y=None,
    batch_size=None,
    epochs=1,
    verbose='auto',
    callbacks=None,
    validation_split=0.0,
    validation_data=None,
    shuffle=True,
    class_weight=None,
    sample_weight=None,
    initial_epoch=0,
    steps_per_epoch=None,
    validation_steps=None,
    validation_batch_size=None,
    validation_freq=1,
    max_queue_size=10,
    workers=1,
    use_multiprocessing=False,
)
Docstring:
Trains the model for a fixed number of epochs (iterations on a dataset).

Args:
    x: Input data. It could be:
      - A Numpy array (or array-like), or a list of arrays
        (in case the model has multiple inputs).
      - A TensorFlow tensor, or a list of tensors
        (in case the model has multiple inputs).
      - A dict mapping input names to the corresponding array/tensors,
        if the model has named inputs.
      - A `tf.data` dataset. Should return a tuple
        of either `(inputs, targets)` or
        `(inputs, targets, sam

In [27]:
print(y_train_classification.shape)
print(y_train_regression.shape)

(1603749, 2)
(1603749, 1)


In [136]:
model.summary()

Model: "my_model_27"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 normalization_27 (Normaliza  multiple                 3         
 tion)                                                           
                                                                 
 dense_208 (Dense)           multiple                  640       
                                                                 
 dense_209 (Dense)           multiple                  8256      
                                                                 
 dense_210 (Dense)           multiple                  2080      
                                                                 
 dense_211 (Dense)           multiple                  33        
                                                                 
 dense_212 (Dense)           multiple                  320       
                                                       