In [1]:
import pandas as pd
dataset = pd.read_csv('D:\\NewFinalDatasetsForNeuralNetwork\\crash_noncrash_combined_csv_09_03_2023__13_24.csv')
dataset

NORMALIZED PEDESTRIAN POSITION X  NORMALIZED PEDESTRIAN POSITION Y  \
0                           -11.434253                              -1.6   
1                            12.465866                              -4.0   
2                            42.308881                              -4.0   
3                           -19.452802                              -0.8   
4                            -1.497305                              -2.6   
...                                ...                               ...   
8257                         17.478287                              -1.5   
8258                          7.499135                              -3.5   
8259                         12.485525                              -1.0   
8260                         48.383731                              -4.6   
8261                         14.484414                              -4.2   

      NORMALIZED PEDESTRIAN DIRECTION  NORMALIZED PEDESTRIAN SPEED       TTC  
0                                 4.3                     1.388889       inf  
1                                 2.5                     1.388889       inf  
2                                 4.5                     1.388889  2.888906  
3                                 1.4                     1.388889       inf  
4                                 0.4                     1.388889       inf  
...                               ...                          ...       ...  
8257                              0.9                     1.388889  1.080133  
8258                              0.1                     1.388889       inf  
8259                              0.9                     1.388889  0.720089  
8260                              1.7                     1.388889  3.313458  
8261                              0.8                     1.388889       inf  

[8262 rows x 5 columns]

In [2]:
import numpy as np

# Create a new column 'TTC Category' and bin values based on their range
bins = [-1, 7, np.inf]
labels = ['crash', 'no_crash']
dataset['SCENARIO TYPE'] = pd.cut(dataset['TTC'], bins=bins, labels=labels)

In [3]:
dataset

NORMALIZED PEDESTRIAN POSITION X  NORMALIZED PEDESTRIAN POSITION Y  \
0                           -11.434253                              -1.6   
1                            12.465866                              -4.0   
2                            42.308881                              -4.0   
3                           -19.452802                              -0.8   
4                            -1.497305                              -2.6   
...                                ...                               ...   
8257                         17.478287                              -1.5   
8258                          7.499135                              -3.5   
8259                         12.485525                              -1.0   
8260                         48.383731                              -4.6   
8261                         14.484414                              -4.2   

      NORMALIZED PEDESTRIAN DIRECTION  NORMALIZED PEDESTRIAN SPEED       TTC  \
0                                 4.3                     1.388889       inf   
1                                 2.5                     1.388889       inf   
2                                 4.5                     1.388889  2.888906   
3                                 1.4                     1.388889       inf   
4                                 0.4                     1.388889       inf   
...                               ...                          ...       ...   
8257                              0.9                     1.388889  1.080133   
8258                              0.1                     1.388889       inf   
8259                              0.9                     1.388889  0.720089   
8260                              1.7                     1.388889  3.313458   
8261                              0.8                     1.388889       inf   

     SCENARIO TYPE  
0         no_crash  
1         no_crash  
2            crash  
3         no_crash  
4         no_crash  
...            ...  
8257         crash  
8258      no_crash  
8259         crash  
8260         crash  
8261      no_crash  

[8262 rows x 6 columns]

In [162]:
# print(dataset.loc[dataset['SCENARIO TYPE'].isna()])

Empty DataFrame
Columns: [NORMALIZED PEDESTRIAN POSITION X, NORMALIZED PEDESTRIAN POSITION Y, NORMALIZED PEDESTRIAN DIRECTION, NORMALIZED PEDESTRIAN SPEED, TTC, SCENARIO TYPE]
Index: []


In [ ]:
# from sklearn import preprocessing
# lb = preprocessing.LabelBinarizer()
# Y = np.array(dataset['SCENARIO TYPE']).astype(str)
# Y_bin = lb.fit_transform(Y) # label binarizer will convert it to a 0/1's
# print(Y_bin)

In [4]:
from sklearn.preprocessing import OneHotEncoder

# Select column to one hot encode
col_to_encode = 'SCENARIO TYPE'

# Perform one hot encoding
one_hot_encoded = pd.get_dummies(dataset[col_to_encode], prefix=col_to_encode)

# Append one hot encoded columns to original dataset
dataset = pd.concat([dataset, one_hot_encoded], axis=1)

# Drop original column that was one hot encoded
dataset = dataset.drop(col_to_encode, axis=1)
dataset

NORMALIZED PEDESTRIAN POSITION X  NORMALIZED PEDESTRIAN POSITION Y  \
0                           -11.434253                              -1.6   
1                            12.465866                              -4.0   
2                            42.308881                              -4.0   
3                           -19.452802                              -0.8   
4                            -1.497305                              -2.6   
...                                ...                               ...   
8257                         17.478287                              -1.5   
8258                          7.499135                              -3.5   
8259                         12.485525                              -1.0   
8260                         48.383731                              -4.6   
8261                         14.484414                              -4.2   

      NORMALIZED PEDESTRIAN DIRECTION  NORMALIZED PEDESTRIAN SPEED       TTC  \
0                                 4.3                     1.388889       inf   
1                                 2.5                     1.388889       inf   
2                                 4.5                     1.388889  2.888906   
3                                 1.4                     1.388889       inf   
4                                 0.4                     1.388889       inf   
...                               ...                          ...       ...   
8257                              0.9                     1.388889  1.080133   
8258                              0.1                     1.388889       inf   
8259                              0.9                     1.388889  0.720089   
8260                              1.7                     1.388889  3.313458   
8261                              0.8                     1.388889       inf   

      SCENARIO TYPE_crash  SCENARIO TYPE_no_crash  
0                       0                       1  
1                       0                       1  
2                       1                       0  
3                       0                       1  
4                       0                       1  
...                   ...                     ...  
8257                    1                       0  
8258                    0                       1  
8259                    1                       0  
8260                    1                       0  
8261                    0                       1  

[8262 rows x 7 columns]

In [5]:
# dataset['SCENARIO TYPE'] = data_transformed
dataset = dataset.drop('TTC', axis=1)
dataset

NORMALIZED PEDESTRIAN POSITION X  NORMALIZED PEDESTRIAN POSITION Y  \
0                           -11.434253                              -1.6   
1                            12.465866                              -4.0   
2                            42.308881                              -4.0   
3                           -19.452802                              -0.8   
4                            -1.497305                              -2.6   
...                                ...                               ...   
8257                         17.478287                              -1.5   
8258                          7.499135                              -3.5   
8259                         12.485525                              -1.0   
8260                         48.383731                              -4.6   
8261                         14.484414                              -4.2   

      NORMALIZED PEDESTRIAN DIRECTION  NORMALIZED PEDESTRIAN SPEED  \
0                                 4.3                     1.388889   
1                                 2.5                     1.388889   
2                                 4.5                     1.388889   
3                                 1.4                     1.388889   
4                                 0.4                     1.388889   
...                               ...                          ...   
8257                              0.9                     1.388889   
8258                              0.1                     1.388889   
8259                              0.9                     1.388889   
8260                              1.7                     1.388889   
8261                              0.8                     1.388889   

      SCENARIO TYPE_crash  SCENARIO TYPE_no_crash  
0                       0                       1  
1                       0                       1  
2                       1                       0  
3                       0                       1  
4                       0                       1  
...                   ...                     ...  
8257                    1                       0  
8258                    0                       1  
8259                    1                       0  
8260                    1                       0  
8261                    0                       1  

[8262 rows x 6 columns]

In [6]:
from sklearn.model_selection import train_test_split

# Split dataset into features and labels
X = dataset.drop(columns=["SCENARIO TYPE_crash", "SCENARIO TYPE_no_crash"]).values
#X = dataset.drop(columns=["SCENARIO TYPE"]).values
#y = dataset[["SCENARIO TYPE"]].values
y = dataset[["SCENARIO TYPE_crash", "SCENARIO TYPE_no_crash"]].values
# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
import tensorflow as tf
import keras
from keras import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
# Defining first layer of the neural network, which normalizes the input data on the fly
normalizer_layer = keras.layers.Normalization(axis=-1)
normalizer_layer = keras.layers.Normalization(input_shape=[4,], axis=None)
# Adapting normalizer layer to the input train data shape
normalizer_layer.adapt(np.array(X_train))

# Defines the model and compilation
def build_and_compile_model(normalizer_layer):
  nn_model = keras.Sequential([
      normalizer_layer,
      keras.layers.Dense(128, activation='relu', kernel_initializer='he_uniform'),
      keras.layers.Dense(64, activation='sigmoid'),
      keras.layers.Dense(32, activation='relu'),
      keras.layers.Dense(y.shape[1], activation="softmax")
  ])

  nn_model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=["categorical_accuracy"])
  return nn_model

In [8]:
classification_model = build_and_compile_model(normalizer_layer)
# Train the model
history = classification_model.fit(X_train, y_train, epochs=300, batch_size=128, validation_data=(X_test, y_test))

# Evaluate the model
loss, accuracy = classification_model.evaluate(X_test, y_test)
print("Test set accuracy:", accuracy)

Epoch 1/300
52/52 [==============================] - 2s 17ms/step - loss: 0.6730 - categorical_accuracy: 0.5747 - val_loss: 0.6487 - val_categorical_accuracy: 0.6993
Epoch 2/300
52/52 [==============================] - 1s 10ms/step - loss: 0.6337 - categorical_accuracy: 0.6951 - val_loss: 0.6206 - val_categorical_accuracy: 0.6945
Epoch 3/300
52/52 [==============================] - 1s 11ms/step - loss: 0.6094 - categorical_accuracy: 0.6951 - val_loss: 0.6003 - val_categorical_accuracy: 0.6921
Epoch 4/300
52/52 [==============================] - 0s 8ms/step - loss: 0.5909 - categorical_accuracy: 0.6909 - val_loss: 0.5841 - val_categorical_accuracy: 0.6903
Epoch 5/300
52/52 [==============================] - 0s 8ms/step - loss: 0.5763 - categorical_accuracy: 0.6906 - val_loss: 0.5714 - val_categorical_accuracy: 0.6933
Epoch 6/300
52/52 [==============================] - 0s 7ms/step - loss: 0.5646 - categorical_accuracy: 0.6913 - val_loss: 0.5615 - val_categorical_accuracy: 0.6921
Epoch 7

In [10]:
classification_model.save('TTC_classification_model.h5')

In [9]:
print(f'{y_test[:10]}\n')
prediction = classification_model.predict(X_test[:10])
print(f'{prediction}\n')
print((prediction.argmax(axis=1)).reshape((-1, 1)))

[[1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]]

1/1 [==============================] - 0s 99ms/step
[[9.9999267e-01 7.2626535e-06]
 [9.9999982e-01 1.4727014e-07]
 [9.9999994e-01 4.6328502e-08]
 [4.0176943e-05 9.9995977e-01]
 [9.9999696e-01 2.9810492e-06]
 [9.9999779e-01 2.1964383e-06]
 [7.0342680e-06 9.9999291e-01]
 [9.9999148e-01 8.4376006e-06]
 [9.9999988e-01 9.4262234e-08]
 [9.9999774e-01 2.2166776e-06]]

[[0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]]
